stages:
  - codestyle
sonar:
  stage: codestyle
  image:
    name: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_AUTH_TOKEN: $SONAR_AUTH_TOKEN
    SONAR_HOST_URL: https://sonar.tkhtechnology.com
  script:
    - sonar-scanner -Dsonar.login=${SONAR_AUTH_TOKEN}
  tags:
    - docker_shared
  only:
    - merge_requests
    - schedules