stages:
  - codestyle
  - Test
sonar:
  stage: codestyle
  image:
    name: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_AUTH_TOKEN: $SONAR_AUTH_TOKEN
    SONAR_HOST_URL: https://sonar.tkhtechnology.com
  script:
    - sonar-scanner -Dsonar.login=${SONAR_AUTH_TOKEN}
  tags:
    - docker_shared
  only:
    - merge_requests
    - schedules
test-1:
  stage: Test
  script:
    - pip install pipenv
    - pipenv install
    - pipenv run pytest test_main.py
  only:
    - merge_requests
    - schedules
